name: CI Pipeline

on:
  push:
    branches: [ main_vhive ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ main_vhive ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:

  build:
    strategy:
      matrix:
        go: ['1.13', '1.14', '1.15', '1.16']
      # Build all variants regardless of failures
      fail-fast: false

    name: Build and check code quality
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # to add commit DCO checks later
        fetch-depth: 21

    - name: Configure AWS credentials using EASE lab account
      uses: aws-actions/configure-aws-credentials@v1
      with:
	aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
	aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
	aws-region: us-west-1

    - name: Check code
      uses: golangci/golangci-lint-action@v2
      with:
        args: --timeout 5m

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: go build -race -v -a ./...

    - name: Run tests
      run: go run -cover -race -v -a ./...
